import type { FunctionalComponent, SVGAttributes } from 'vue'
import {
	ArchiveIcon,
	BellIcon,
	BookIcon,
	BookOpenIcon,
	BoxIcon,
	CalendarIcon,
	ChangeSkinIcon,
	ChartIcon,
	CloudIcon,
	CodeIcon,
	CompassIcon,
	CrownIcon,
	DashboardIcon,
	DownloadIcon,
	ExternalIcon,
	FileTextIcon,
	FlaskConicalIcon,
	FolderIcon,
	GiftIcon,
	GlobeIcon,
	GridIcon,
	HammerIcon,
	HeartIcon,
	HomeIcon,
	ImageIcon,
	InfoIcon,
	LibraryIcon,
	LinkIcon,
	ListIcon,
	MapIcon,
	MessageIcon,
	NewspaperIcon,
	PaletteIcon,
	PinIcon,
	PlugIcon,
	RocketIcon,
	SearchIcon,
	ServerIcon,
	SettingsIcon,
	ShieldIcon,
	StarIcon,
	UploadIcon,
	UserIcon,
	UsersIcon,
	VideoIcon,
	WorldIcon,
	WrenchIcon,
} from '@modrinth/assets'

type NavIconComponent = FunctionalComponent<SVGAttributes>

/**
 * Domain manifest 导航图标解析：同时识别启动器原生 token
 * （home/discover…）与管理台图标选择器写入的 Remix 名。
 * 未命中的值回落地球图标，避免侧栏出现空白按钮。
 */
const YMCL_NAV_ICON_MAP: Record<string, NavIconComponent> = {
	// native tokens (YmclNativePages + admin Chinese/English aliases)
	home: HomeIcon,
	homepage: HomeIcon,
	'首页': HomeIcon,
	discover: CompassIcon,
	explore: CompassIcon,
	'发现': CompassIcon,
	'发现内容': CompassIcon,
	library: LibraryIcon,
	instances: LibraryIcon,
	'实例库': LibraryIcon,
	skins: ChangeSkinIcon,
	skin: ChangeSkinIcon,
	'皮肤': ChangeSkinIcon,
	lab: FlaskConicalIcon,
	'实验': FlaskConicalIcon,
	downloads: DownloadIcon,
	'下载': DownloadIcon,
	settings: SettingsIcon,
	'设置': SettingsIcon,
	worlds: WorldIcon,
	'世界': WorldIcon,
	activities: CalendarIcon,
	activity: CalendarIcon,
	'活动': CalendarIcon,
	tasks: ListIcon,
	task: ListIcon,
	'任务': ListIcon,
	'我的任务': ListIcon,
	stats: ChartIcon,
	'统计': ChartIcon,

	// Remix aliases used by the admin icon picker
	'i-ri:home-4-line': HomeIcon,
	'i-ri:home-smile-line': HomeIcon,
	'i-ri:compass-3-line': CompassIcon,
	'i-ri:compass-line': CompassIcon,
	'i-ri:search-line': SearchIcon,
	'i-ri:star-line': StarIcon,
	'i-ri:heart-line': HeartIcon,
	'i-ri:fire-line': ChartIcon,
	'i-ri:trending-up-line': ChartIcon,
	'i-ri:server-2-line': ServerIcon,
	'i-ri:server-line': ServerIcon,
	'i-ri:hard-drive-line': ServerIcon,
	'i-ri:box-3-line': BoxIcon,
	'i-ri:archive-line': ArchiveIcon,
	'i-ri:folder-line': FolderIcon,
	'i-ri:folder-open-line': FolderIcon,
	'i-ri:book-2-line': BookIcon,
	'i-ri:book-open-line': BookOpenIcon,
	'i-ri:newspaper-line': NewspaperIcon,
	'i-ri:article-line': FileTextIcon,
	'i-ri:file-text-line': FileTextIcon,
	'i-ri:calendar-line': CalendarIcon,
	'i-ri:calendar-event-line': CalendarIcon,
	'i-ri:list-check-3': ListIcon,
	'i-ri:checkbox-circle-line': ListIcon,
	'i-ri:todo-line': ListIcon,
	'i-ri:gamepad-line': GridIcon,
	'i-ri:gamepad-fill': GridIcon,
	'i-ri:shirt-line': ChangeSkinIcon,
	'i-ri:user-smile-line': UserIcon,
	'i-ri:team-line': UsersIcon,
	'i-ri:group-line': UsersIcon,
	'i-ri:chat-3-line': MessageIcon,
	'i-ri:forum-line': MessageIcon,
	'i-ri:question-line': InfoIcon,
	'i-ri:information-line': InfoIcon,
	'i-ri:lightbulb-line': InfoIcon,
	'i-ri:flask-line': FlaskConicalIcon,
	'i-ri:magic-line': RocketIcon,
	'i-ri:puzzle-line': PlugIcon,
	'i-ri:plug-line': PlugIcon,
	'i-ri:settings-3-line': SettingsIcon,
	'i-ri:tools-line': WrenchIcon,
	'i-ri:download-2-line': DownloadIcon,
	'i-ri:upload-2-line': UploadIcon,
	'i-ri:cloud-line': CloudIcon,
	'i-ri:earth-line': WorldIcon,
	'i-ri:map-pin-line': PinIcon,
	'i-ri:map-2-line': MapIcon,
	'i-ri:building-line': DashboardIcon,
	'i-ri:hammer-line': HammerIcon,
	'i-ri:sword-line': ShieldIcon,
	'i-ri:shield-line': ShieldIcon,
	'i-ri:bolt-line': RocketIcon,
	'i-ri:leaf-line': GlobeIcon,
	'i-ri:music-2-line': MessageIcon,
	'i-ri:image-line': ImageIcon,
	'i-ri:video-line': VideoIcon,
	'i-ri:trophy-line': CrownIcon,
	'i-ri:gift-line': GiftIcon,
	'i-ri:shopping-bag-line': GiftIcon,
	'i-ri:money-cny-circle-line': CrownIcon,
	'i-ri:vip-crown-line': CrownIcon,
	'i-ri:notification-3-line': BellIcon,
	'i-ri:megaphone-line': BellIcon,
	'i-ri:rocket-2-line': RocketIcon,
	'i-ri:dashboard-3-line': DashboardIcon,
	'i-ri:layout-masonry-line': GridIcon,
	'i-ri:palette-line': PaletteIcon,
	'i-ri:code-box-line': CodeIcon,
	'i-ri:terminal-box-line': CodeIcon,
	'i-ri:link': LinkIcon,
	'i-ri:external-link-line': ExternalIcon,
	'i-ri:more-line': ListIcon,
	'i-ri:apps-2-line': GridIcon,
	'i-ri:menu-line': ListIcon,
	'i-ri:node-tree': ListIcon,
}

export function resolveYmclNavIcon(icon?: string | null): NavIconComponent {
	const key = icon?.trim() ?? ''
	if (!key) return GlobeIcon
	return YMCL_NAV_ICON_MAP[key] ?? GlobeIcon
}
